name: Upload Roblox Randomizer

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace YOUR_API_KEY in robloxrandomizers.py
      run: |
        sed -i "s|YOUR_API_KEY|${{ secrets.YOUR_API_KEY }}|g" robloxrandomizer.py
        sed -i "s|YOUR_API_KEY|${{ secrets.YOUR_API_KEY }}|g" robloxrandomizerplus.py
        
    - name: Verify API key replaced
      run: |
        grep "YOUR_API_KEY" robloxrandomizer.py && echo "API key NOT replaced in robloxrandomizer.py" || echo "API key replaced successfully in robloxrandomizer.py"
        grep "YOUR_API_KEY" robloxrandomizerplus.py && echo "API key NOT replaced in robloxrandomizerplus.py" || echo "API key replaced successfully in robloxrandomizerplus.py"
    
    - name: Zip the project
      run: |
        zip -r robloxrandomizer.zip . -x "*.git*"

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: robloxrandomizer
        path: robloxrandomizer.zip
